### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by agentcooper** [agentcooper/htmltemplate-vdom#3]
List of tags yet to be supported:
- [x] `TMPL_INLINE`, `TMPL_INCLUDE`
- [x] `TMPL_ASSIGN`
- [x] `TMPL_BLOCK`
- [x] `TMPL_UNLESS`
- [x] `TMPL_SETVAR`
- [x] `TMPL_FOR`
- [x] `TMPL_WS`
- [x] `TMPL_MARKER`
- [x] `TMPL_BREAK`
- [x] `TMPL_CONTINUE`
- [ ] `TMPL_WITH`

**Comment by Lapple** [comment]
I propose to resolve `TMPL_CONTINUE` by applying a transform, see [implementation](https://github.com/Lapple/htmltemplate-transform/blob/master/plugins/replace-continue.js), [tests](https://github.com/Lapple/htmltemplate-transform/tree/master/test/replace-continue)

**Comment by agentcooper** [comment]
What about `TMPL_BREAK`?

**Comment by Lapple** [comment]
Maybe `TMPL_BREAK` is just a `TMPL_CONTINUE` with setting a flag on top of the loop body. E.g.:

``` xml
<TMPL_LOOP items>
    <div class="content"><!-- ... --></div>
    <TMPL_IF terminate>
        <TMPL_BREAK>
    </TMPL_IF>
</TMPL_LOOP>
```

can be transformed into

``` xml
<TMPL_LOOP items>
    <TMPL_UNLESS __terminate__>
        <div class="content"><!-- ... --></div>
        <TMPL_IF terminate>
            <TMPL_ASSIGN __terminate__ [% 1 %]>
            <TMPL_CONTINUE>
        </TMPL_IF>
    </TMPL_UNLESS>
</TMPL_LOOP>
```

**Comment by agentcooper** [comment]
Every tag is implemented now, except `TMPL_WITH` which we don't want to support.
